"""empty message

Revision ID: 5f9c64645985
Revises: 0961ffc974d0
Create Date: 2022-07-06 00:35:19.613355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9c64645985'
down_revision = '0961ffc974d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('img_file', sa.Text(), nullable=True),
    sa.Column('img_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_product_id'], ['product.prod_id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_file', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('prod_file')

    op.drop_table('image')
    # ### end Alembic commands ###
