"""product table

Revision ID: 6928bd863367
Revises: c0ed469e7887
Create Date: 2022-06-12 21:38:44.801923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6928bd863367'
down_revision = 'c0ed469e7887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('bra_id', sa.Integer(), nullable=False),
    sa.Column('bra_name', sa.Text(), nullable=True),
    sa.Column('bra_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bra_id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_bra_name'), ['bra_name'], unique=True)

    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=600), nullable=True),
    sa.Column('cat_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('cat_name')
    )
    op.create_table('discounts',
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('disc_name', sa.Text(), nullable=False),
    sa.Column('disc_percent', sa.Float(), nullable=False),
    sa.Column('disc_active', sa.Boolean(), nullable=False),
    sa.Column('disc_created', sa.DateTime(), nullable=False),
    sa.Column('disc_modified', sa.DateTime(), nullable=False),
    sa.Column('disc_deleted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('disc_id'),
    sa.UniqueConstraint('disc_name')
    )
    op.create_table('product',
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=3000), nullable=False),
    sa.Column('prod_price', sa.Float(), nullable=False),
    sa.Column('prod_desc', sa.Text(), nullable=False),
    sa.Column('prod_quantity', sa.Integer(), nullable=False),
    sa.Column('prod_image', sa.Text(), nullable=True),
    sa.Column('prod_category_id', sa.Integer(), nullable=True),
    sa.Column('prod_discounts_id', sa.Integer(), nullable=True),
    sa.Column('prod_created', sa.DateTime()),
    sa.Column('prod_modified', sa.DateTime()),
    sa.Column('prod_deleted', sa.DateTime()),
    sa.Column('prod_brand_id', sa.Integer()),
    sa.ForeignKeyConstraint(['prod_brand_id'], ['brands.bra_id'], ),
    sa.ForeignKeyConstraint(['prod_category_id'], ['categories.cat_id'], ),
    sa.ForeignKeyConstraint(['prod_discounts_id'], ['discounts.disc_id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('discounts')
    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_bra_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
