"""user table

Revision ID: 7263e611883d
Revises: 
Create Date: 2022-08-24 23:59:16.167427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7263e611883d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('bra_id', sa.Integer(), nullable=False),
    sa.Column('bra_name', sa.Text(), nullable=True),
    sa.Column('bra_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bra_id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_bra_name'), ['bra_name'], unique=True)

    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=600), nullable=True),
    sa.Column('cat_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('cat_name')
    )
    op.create_table('discounts',
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('disc_name', sa.Text(), nullable=False),
    sa.Column('disc_percent', sa.Float(), nullable=False),
    sa.Column('disc_active', sa.Boolean(), nullable=False),
    sa.Column('disc_created', sa.DateTime(), nullable=True),
    sa.Column('disc_modified', sa.DateTime(), nullable=True),
    sa.Column('disc_deleted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('disc_id'),
    sa.UniqueConstraint('disc_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('product',
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=3000), nullable=False),
    sa.Column('prod_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('prod_desc', sa.Text(), nullable=False),
    sa.Column('prod_quantity', sa.Integer(), nullable=False),
    sa.Column('prod_category_id', sa.Integer(), nullable=True),
    sa.Column('prod_file', sa.Text(), nullable=True),
    sa.Column('prod_discounts_id', sa.Integer(), nullable=True),
    sa.Column('prod_created', sa.DateTime(), nullable=True),
    sa.Column('prod_modified', sa.DateTime(), nullable=True),
    sa.Column('prod_deleted', sa.DateTime(), nullable=True),
    sa.Column('prod_brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_brand_id'], ['brands.bra_id'], ),
    sa.ForeignKeyConstraint(['prod_category_id'], ['categories.cat_id'], ),
    sa.ForeignKeyConstraint(['prod_discounts_id'], ['discounts.disc_id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('image',
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('img_file', sa.Text(), nullable=True),
    sa.Column('img_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_product_id'], ['product.prod_id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('user_roles')
    op.drop_table('product')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('roles')
    op.drop_table('discounts')
    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_bra_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
