"""table comment

Revision ID: 908c99d5eb6d
Revises: fcd12d3e1315
Create Date: 2022-09-03 02:53:44.361093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908c99d5eb6d'
down_revision = 'fcd12d3e1315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('com_id', sa.Integer(), nullable=False),
    sa.Column('com_user_id', sa.Integer(), nullable=False),
    sa.Column('com_comment', sa.String(length=5000), nullable=True),
    sa.Column('com_product_id', sa.Integer(), nullable=True),
    sa.Column('com_create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['com_product_id'], ['product.prod_id'], ),
    sa.ForeignKeyConstraint(['com_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('com_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
